//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoDACNPMNC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMENT
    {
        public int id_cmt { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> MaDT { get; set; }
        public string content_cmt { get; set; }
        public Nullable<int> stars { get; set; }
        public Nullable<System.DateTime> time_cmt { get; set; }
    
        public virtual user user { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
