//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoDACNPMNC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class profile
    {
        public int id_profile { get; set; }
        public Nullable<int> id_user { get; set; }
        public string names { get; set; }
        public string phone { get; set; }
        public string addres { get; set; }
        public string avatar { get; set; }
    
        public virtual user user { get; set; }
    }
}
