//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace He_thong_ban_DT_online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAI
    {
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> BrandId { get; set; }
    
        public virtual BRAND BRAND { get; set; }
    }
}
