//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace He_thong_ban_DT_online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CTDATHANGs = new HashSet<CTDATHANG>();
            this.DANHGIASPs = new HashSet<DANHGIASP>();
            this.HINHANHs = new HashSet<HINHANH>();
        }
    
        public int MaSP { get; set; }
        public string TenDT { get; set; }
        public string MoTa { get; set; }
        public string HinhMinhHoa { get; set; }
        public Nullable<int> MaBrand { get; set; }
        public Nullable<int> MaNSX { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> SoluongTon { get; set; }
        public Nullable<int> SoluongBan { get; set; }
        public Nullable<int> SolanXem { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<decimal> Dongia { get; set; }
        public string MauSac { get; set; }
        public string ManHinh { get; set; }
        public string CauHinh { get; set; }
        public string BoNhoTrong { get; set; }
        public string Camera_main { get; set; }
        public string HeDieuHanh { get; set; }
        public string TheSim { get; set; }
        public string DungLuongPin { get; set; }
        public Nullable<int> DungLuongRam { get; set; }
        public string CongNgheSac { get; set; }
        public string DoPhanGiai { get; set; }
        public string CongSac { get; set; }
        public Nullable<int> BaoHanh { get; set; }
        public string KichThuoc { get; set; }
        public Nullable<decimal> KhoiLuong { get; set; }
        public Nullable<System.DateTime> NgaySX { get; set; }
    
        public virtual BRAND BRAND { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDATHANG> CTDATHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHGIASP> DANHGIASPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HINHANH> HINHANHs { get; set; }
        public virtual NHASANXUAT NHASANXUAT { get; set; }
    }
}
